name: bezier_chart_plus
description: Beautiful curvy charts for flutter.
version: 0.0.1
homepage: https://github.com/pacifio/bezier_chart_plus

environment:
  sdk: ">=3.0.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
